-- Run this once in Supabase SQL Editor.
create table if not exists public.settings (
  key text primary key,
  value text not null
);

create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  storage_path text not null,
  description text not null,
  photo_date date not null,
  is_cube boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.oviman (
  id bigint generated by default as identity primary key,
  oviman_date date not null,
  reason text not null,
  solution text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.promises (
  id bigint generated by default as identity primary key,
  promise_text text not null,
  promise_date date,
  created_at timestamptz not null default now()
);

create table if not exists public.meetups (
  id bigint generated by default as identity primary key,
  meetup_date date not null,
  places text not null,
  foods text not null,
  created_at timestamptz not null default now()
);

insert into public.settings(key,value)
values ('story','এখানে আমাদের গল্প লিখে রাখো ❤️')
on conflict (key) do nothing;

-- The Flask server uses the Supabase service-role key.
-- Keep SUPABASE_SERVICE_ROLE_KEY only in Render environment variables.
